### ISSUE TITLE
Error related to "request" library prevents use

### ISSUE THREAD

**Issue by Joncom** [lmammino/godaddy-dns#25]
```
$ node --version
v9.2.1

$ sudo npm install godaddy-dns -g
/usr/local/bin/godaddy-dns -> /usr/local/lib/node_modules/godaddy-dns/src/cli.js
+ godaddy-dns@1.2.0
updated 1 package in 6.052s

$ godaddy-dns -v

###
### The "request" library is not installed automatically anymore.
### But required by "request-promise".
###
### npm install request --save
###

/usr/local/lib/node_modules/godaddy-dns/node_modules/aws4/lru.js:1
(function (exports, require, module, __filename, __dirname) {


SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/godaddy-dns/node_modules/aws4/aws4.js:5:11)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/godaddy-dns/node_modules/request/request.js:11:12)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
```

**Comment by Joncom** [comment]
Nevermind. Seems that installing npm packages globally while using [n](https://github.com/tj/n) to manage NodeJS installations is somewhat sketchy prospect. Managed to get everything working fine by installing to a specific folder (not globally), and executing godaddy-dns directly from there.

**Comment by lmammino** [comment]
Hello @Joncom, thanks for reporting the issue anyway, I'll try to check if I can replicate the bug and see if there's something I can do to avoid the issue with that specific setup.

Anyway, you might also be interested in knowing that in the [latest releases](https://github.com/lmammino/godaddy-dns/releases) you can download binaries that should just work in your OS without even having to worry about Node.js and dependencies.

Let me know if you have further issues.

**Comment by papajo** [comment]
I just ran into this issue. It worked fine during first few trial test runs then it started puking these errors..whatever.
